package org.example.view;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.Arrays;

public class AddRoomUI extends JDialog {
    private final ActionListener ac;
    private final String title;

    private final String[] lisTypeClass = {"Phòng thực hành", "Phòng lý thuyết"};
    private final String[] listLocation = {"A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12"};

    private final String[] listStatus = {"Chưa được mượn", "Đang chờ xác nhận", "Đã được mượn"};
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JTextField nameClassTextField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JButton submitComboBox;
    private javax.swing.JComboBox<String> typeClassComboBox;
    public AddRoomUI(java.awt.Frame parent, boolean modal, ActionListener ac, String actionCommand) {
        super(parent, modal);
        this.ac = ac;
        this.title = "Thêm mới phòng học";
        initComponents(false, actionCommand);

    }
    public AddRoomUI(java.awt.Frame parent, boolean modal, ActionListener ac, String title, String actionCommand) {
        super(parent, modal);
        this.ac = ac;
        this.title = title;
        initComponents(true, actionCommand);

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(boolean isEdit, String actionCommand) {
        setLocationRelativeTo(null);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameClassTextField = new javax.swing.JTextField();
        typeClassComboBox = new javax.swing.JComboBox<>();
        locationComboBox = new javax.swing.JComboBox<>();
        submitComboBox = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setText("Trạng thái");
        statusComboBox = new javax.swing.JComboBox<>();
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(listStatus));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên phòng");

        jLabel2.setText("Loại phòng");

        jLabel3.setText("Vị trí");

        typeClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(lisTypeClass));

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(listLocation));
        submitComboBox.setText("Xác nhận");
        submitComboBox.addActionListener(ac);
        submitComboBox.setActionCommand(actionCommand);
        jLabel4.setText(title);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(typeClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(nameClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(typeClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(submitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(90, Short.MAX_VALUE))
        );
        if (!isEdit) {
            jLabel5.setVisible(false);
            statusComboBox.setVisible(false);
        }
        pack();
    }// </editor-fold>

    public void setTypeClassComboBox(int type) {
        typeClassComboBox.setSelectedIndex(type - 1);
    }
    public void setStatusComboBox(int status) {
        statusComboBox.setSelectedIndex(status - 1);
    }
    public void setLocationComboBox(String location) {
        for(int i = 0; i < listLocation.length; i++) {
            if(listLocation[i].equals(location)) {
                locationComboBox.setSelectedIndex(i);
            }
        }
    }
    public String getClassName() {
        return nameClassTextField.getText();
    }

    // End of variables declaration
    public void setClassName(String data) {
        nameClassTextField.setText(data);
    }

    public int getTypeClass() {
        if (typeClassComboBox.getSelectedItem().equals("Phòng lý thuyết")) {
            return 2;
        }
        return 1;
    }

    public String getLocate() {
        return (String) locationComboBox.getSelectedItem();
    }
    public int getStatus() {
        return statusComboBox.getSelectedIndex() + 1;
    }
}
