package org.example.view;

import org.example.model.Room;

import java.util.List;

public class Summary extends javax.swing.JDialog {

    /**
     * Creates new form Summary
     */
    public Summary(java.awt.Frame parent, boolean modal, List<Room> listRoom) {
        super(parent, modal);
        this.listRoom = listRoom;
        initComponents(listRoom);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(List<Room> listRoom) {
        int countUnUse = 0;
        int countWait = 0;
        int countUse = 0;
        for (Room room:
             listRoom) {
            if(room.getStatus() == 1) {
                ++countUnUse;
            }
            else if (room.getStatus() == 2) {
                ++countWait;
            }
            else {
                ++countUse;
            }
        }
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unuse = new javax.swing.JLabel();
        wait = new javax.swing.JLabel();
        use = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Phòng chưa được mượn");

        jLabel2.setText("Phòng đang chờ xác nhận");

        jLabel3.setText("Phòng đang được sử dụng");

        unuse.setText("Có " + countUnUse + " phòng chiếm " + ((countUnUse * 100) /listRoom.size()) + "%");

        wait.setText("Có " + countWait + " phòng chiếm " + ((countWait * 100) /listRoom.size()) + "%");

        use.setText("Có " + countUse + " phòng chiếm " + ((countUse * 100) /listRoom.size()) + "%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wait)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(62, 62, 62)
                                                                .addComponent(unuse))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(use)))))
                                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(unuse))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(wait))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(use))
                                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel unuse;
    private javax.swing.JLabel use;
    private javax.swing.JLabel wait;
    private List<Room> listRoom;
    // End of variables declaration
}