package org.example.view;

import org.example.model.Room;

public class ViewDetail extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetail
     */
    public ViewDetail(java.awt.Frame parent, boolean modal, Room room) {
        super(parent, modal);
        initComponents(room);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Room room) {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        classNameViewDetail = new javax.swing.JLabel();
        typeClassViewDetail = new javax.swing.JLabel();
        statusViewDetail = new javax.swing.JLabel();
        locationViewDetail = new javax.swing.JLabel();
        userViewDetail = new javax.swing.JLabel();
        dateViewDetail = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lessonsViewDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên phòng");

        jLabel2.setText("Loại phòng");

        jLabel3.setText("Trạng thái");

        jLabel4.setText("Toà nhà");

        jLabel5.setText("Người đăng kí");

        jLabel6.setText("Ngày đăng kí");

        classNameViewDetail.setText(room.getName());

        switch (room.getType()) {
            case 1:
                typeClassViewDetail.setText("Phòng lý thuyết");
                break;
            case 2:
                typeClassViewDetail.setText("Phòng thực hành");
                break;
        }
        switch (room.getStatus()) {
            case 1:
                statusViewDetail.setText("Chưa được mượn");
                break;
            case 2:
                statusViewDetail.setText("Chờ xác nhận");
                break;
            case 3:
                statusViewDetail.setText("Đã được mượn");
                break;
        }
        locationViewDetail.setText(room.getLocation());

        userViewDetail.setText(room.getUserOrder());

        dateViewDetail.setText(room.getDate());

        jLabel13.setText("Tiết đăng kí");

        lessonsViewDetail.setText(room.toStringLessons());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel13))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lessonsViewDetail)
                                        .addComponent(dateViewDetail)
                                        .addComponent(userViewDetail)
                                        .addComponent(locationViewDetail)
                                        .addComponent(statusViewDetail)
                                        .addComponent(typeClassViewDetail)
                                        .addComponent(classNameViewDetail))
                                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(classNameViewDetail))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(typeClassViewDetail))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(statusViewDetail))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(locationViewDetail))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(userViewDetail))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dateViewDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lessonsViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JLabel classNameViewDetail;
    private javax.swing.JLabel dateViewDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lessonsViewDetail;
    private javax.swing.JLabel locationViewDetail;
    private javax.swing.JLabel statusViewDetail;
    private javax.swing.JLabel typeClassViewDetail;
    private javax.swing.JLabel userViewDetail;
    // End of variables declaration
}